<?php
	include("components/_head.php");
	include('components/m-modal__menu.php');
	include('components/m-modal__search.php');
	include('components/m-modal__qr.php');
	include('components/m-modal__convite.php');
	include("components/l-nav.php");
	include($file);
	include("components/l-footer.php");
	include("components/_end.php");
?>